apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudship-deployment
  namespace: cloudship
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudship
  template:
    metadata:
      labels:
        app: cloudship
    spec:
      containers:
      - name: cloudship
        image: rushipanchal/cloudship:latest
        ports:
        - containerPort: 5000
