apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudship-ingress
spec:
  rules:
  - host: cloudship.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cloudship-service
            port:
              number: 80
