apiVersion: v1
kind: Service
metadata:
  name: cloudship-service
  namespace: cloudship
spec:
  type: NodePort
  selector:
    app: cloudship
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30080
