apiVersion: v1
kind: Service
metadata:
  name: cloudship-service
  namespace: cloudship
  labels:
    app: cloudship
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /health
spec:
  type: ClusterIP
  selector:
    app: cloudship
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
